version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bankcards-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bank_cards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - bankcards-network

  app:
    build: .
    container_name: bankcards-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_cards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/migration/db.changelog-master.yml
      SPRING_LIQUIBASE_DEFAULT_SCHEMA: bankcards
      APP_JWT_SECRET: v3ry_s3cur3_and_l0ng_s3cr3t_k3y_with_32_chr_min
      APP_JWT_TOKENEXPIRATION: 1h
    networks:
      - bankcards-network

volumes:
  pg_data:

networks:
  bankcards-network:
